// Code generated by the Lingua Franca compiler from:
// file://home/u-tajima/lf-test/src200/DeadlineTest2.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-o", "60", "sec" };
void lf_set_default_command_line_options() {
        default_argc = 4;
        default_argv = _lf_default_argv;
}
#include "_source.h"
#include "_destination.h"
#include "_deadlinetest2_main.h"
typedef enum {
    deadlinetest2_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[deadlinetest2_main],"deadlinetest2_main",deadlinetest2_main,_lf_number_of_workers,1,0,1,0,1,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `deadlinetest2_main_downstream`
#define DEADLINETEST2_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int deadlinetest2_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `deadlinetest2_main_upstream`
#define DEADLINETEST2_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int deadlinetest2_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t deadlinetest2_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case deadlinetest2_main:
            num_upstream = DEADLINETEST2_MAIN_NUM_UPSTREAM;
            upstream = &deadlinetest2_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case deadlinetest2_main:
            num_downstream = DEADLINETEST2_MAIN_NUM_DOWNSTREAM;
            downstream = &deadlinetest2_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case deadlinetest2_main:
            num_upstream = DEADLINETEST2_MAIN_NUM_UPSTREAM;
            delay = &deadlinetest2_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _deadlinetest2_main_main_self_t* deadlinetest2_main_self[1];
    SUPPRESS_UNUSED_WARNING(deadlinetest2_main_self);
    _source_self_t* deadlinetest2_s_self[1];
    SUPPRESS_UNUSED_WARNING(deadlinetest2_s_self);
    _destination_self_t* deadlinetest2_d_self[1];
    SUPPRESS_UNUSED_WARNING(deadlinetest2_d_self);
    // ***** Start initializing DeadlineTest2 of class DeadlineTest2
    deadlinetest2_main_self[0] = new__deadlinetest2_main();
    deadlinetest2_main_self[0]->base.environment = &environments[deadlinetest2_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    
    #if !defined LF_SINGLE_THREADED
    deadlinetest2_main_self[0]->base.reactor_mutex = NULL;
    #endif
    {
        _deadlinetest2_main_main_self_t *self = deadlinetest2_main_self[0];
        // ***** Start initializing DeadlineTest2.s of class Source
        deadlinetest2_s_self[0] = new__source();
        deadlinetest2_s_self[0]->base.environment = &environments[deadlinetest2_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        deadlinetest2_s_self[0]->period = MSEC(1);
        
        
        // width of -2 indicates that it is not a multiport.
        deadlinetest2_s_self[0]->_lf_y_width = -2;
        { // For scoping
            static int _initial = 0;
            deadlinetest2_s_self[0]->count = _initial;
        } // End scoping.
        { // For scoping
            static int64_t _initial = -1;
            deadlinetest2_s_self[0]->last_send_time = _initial;
        } // End scoping.
        // Initiaizing timer DeadlineTest2.s.t.
        deadlinetest2_s_self[0]->_lf__t.offset = 0;
        deadlinetest2_s_self[0]->_lf__t.period = MSEC(1);
        // Associate timer with the environment of its parent
        environments[deadlinetest2_main].timer_triggers[timer_triggers_count[deadlinetest2_main]++] = &deadlinetest2_s_self[0]->_lf__t;
        deadlinetest2_s_self[0]->_lf__t.mode = NULL;
    
        deadlinetest2_s_self[0]->_lf__reaction_0.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        deadlinetest2_s_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing DeadlineTest2.s
    }
    {
        _deadlinetest2_main_main_self_t *self = deadlinetest2_main_self[0];
        // ***** Start initializing DeadlineTest2.d of class Destination
        deadlinetest2_d_self[0] = new__destination();
        deadlinetest2_d_self[0]->base.environment = &environments[deadlinetest2_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        deadlinetest2_d_self[0]->timeout = USEC(55);
        // width of -2 indicates that it is not a multiport.
        deadlinetest2_d_self[0]->_lf_x_width = -2;
        environments[deadlinetest2_main].shutdown_reactions[shutdown_reaction_count[deadlinetest2_main]++] = &deadlinetest2_d_self[0]->_lf__reaction_1;
        { // For scoping
            static int _initial = 0;
            deadlinetest2_d_self[0]->count = _initial;
        } // End scoping.
        { // For scoping
            static int _initial = 0;
            deadlinetest2_d_self[0]->deadline_miss_count = _initial;
        } // End scoping.
        { // For scoping
            static int _initial = 0;
            deadlinetest2_d_self[0]->total_received = _initial;
        } // End scoping.
        { // For scoping
            static int _initial = 300;
            deadlinetest2_d_self[0]->max_count = _initial;
        } // End scoping.
    
        deadlinetest2_d_self[0]->_lf__reaction_0.deadline = USEC(55);
        deadlinetest2_d_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        deadlinetest2_d_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing DeadlineTest2.d
    }
    //***** End initializing DeadlineTest2
    // **** Start deferred initialize for DeadlineTest2
    {
        deadlinetest2_main_self[0]->base.name = "DeadlineTest2";
        deadlinetest2_main_self[0]->base.parent = (self_base_t*)NULL;
    
    
    
        // **** Start deferred initialize for DeadlineTest2.s
        {
            deadlinetest2_s_self[0]->base.name = "s";
            deadlinetest2_s_self[0]->base.parent = (self_base_t*)deadlinetest2_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of DeadlineTest2.s.
            deadlinetest2_s_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            deadlinetest2_s_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &deadlinetest2_s_self[0]->base.allocations);
            deadlinetest2_s_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &deadlinetest2_s_self[0]->base.allocations);
            deadlinetest2_s_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &deadlinetest2_s_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    deadlinetest2_s_self[0]->_lf__reaction_0.output_produced[count++] = &deadlinetest2_s_self[0]->_lf_y.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of DeadlineTest2.s
        
        }
        // **** End of deferred initialize for DeadlineTest2.s
        // **** Start deferred initialize for DeadlineTest2.d
        {
            deadlinetest2_d_self[0]->base.name = "d";
            deadlinetest2_d_self[0]->base.parent = (self_base_t*)deadlinetest2_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of DeadlineTest2.d.
            deadlinetest2_d_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of DeadlineTest2.d
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of DeadlineTest2.d.
            deadlinetest2_d_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of DeadlineTest2.d
        
        }
        // **** End of deferred initialize for DeadlineTest2.d
    }
    // **** End of deferred initialize for DeadlineTest2
    // **** Start non-nested deferred initialize for DeadlineTest2
    {
    
    
    
        // **** Start non-nested deferred initialize for DeadlineTest2.s
        {
        
            // For reference counting, set num_destinations for port DeadlineTest2.s.y.
            // Iterate over range DeadlineTest2.s.y(0,1)->[DeadlineTest2.d.x(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                deadlinetest2_s_self[src_runtime]->_lf_y._base.num_destinations = 1;
                deadlinetest2_s_self[src_runtime]->_lf_y._base.source_reactor = (self_base_t*)deadlinetest2_s_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range DeadlineTest2.s.y(0,1)->[DeadlineTest2.d.x(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of DeadlineTest2.s triggers 1 downstream reactions
                    // through port DeadlineTest2.s.y.
                    deadlinetest2_s_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of DeadlineTest2.s, allocate an
                    // array of trigger pointers for downstream reactions through port DeadlineTest2.s.y
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &deadlinetest2_s_self[src_runtime]->base.allocations); 
                    deadlinetest2_s_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges DeadlineTest2.s.y(0,1)->[DeadlineTest2.d.x(0,1)] and DeadlineTest2.d.x(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range DeadlineTest2.d.x(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port DeadlineTest2.d.x's trigger struct.
                        deadlinetest2_s_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &deadlinetest2_d_self[dst_runtime]->_lf__x;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for DeadlineTest2.s
        // **** Start non-nested deferred initialize for DeadlineTest2.d
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for DeadlineTest2.d
    }
    // **** End of non-nested deferred initialize for DeadlineTest2
    // Connect inputs and outputs for reactor DeadlineTest2.
    // Connect inputs and outputs for reactor DeadlineTest2.s.
    // Connect DeadlineTest2.s.y(0,1)->[DeadlineTest2.d.x(0,1)] to port DeadlineTest2.d.x(0,1)
    // Iterate over ranges DeadlineTest2.s.y(0,1)->[DeadlineTest2.d.x(0,1)] and DeadlineTest2.d.x(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range DeadlineTest2.d.x(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            deadlinetest2_d_self[dst_runtime]->_lf_x = (_destination_x_t*)&deadlinetest2_s_self[src_runtime]->_lf_y;
        }
    }
    // Connect inputs and outputs for reactor DeadlineTest2.d.
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port DeadlineTest2.s.y to array of is_present fields.
            environments[deadlinetest2_main].is_present_fields[(0) * 1 + 0 + count] = &deadlinetest2_s_self[0]->_lf_y.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port DeadlineTest2.s.y to array of intended_tag fields.
            environments[deadlinetest2_main]._lf_intended_tag_fields[(0) * 1 + 0 + count] = &deadlinetest2_s_self[0]->_lf_y.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance DeadlineTest2
    {
    
        // Set reaction priorities for ReactorInstance DeadlineTest2.s
        {
            // index is the OR of level 0 and 
            // deadline 55000 shifted left 16 bits.
            deadlinetest2_s_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(55000, 0);
        }
    
    
        // Set reaction priorities for ReactorInstance DeadlineTest2.d
        {
            // index is the OR of level 1 and 
            // deadline 55000 shifted left 16 bits.
            deadlinetest2_d_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(55000, 1);
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            deadlinetest2_d_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 2);
        }
    
    }
    
    // Initialize the scheduler for enclave `deadlinetest2_main` in a private scope
    {
        size_t num_reactions_per_level[3] = {1, 1, 1};
        sched_params_t sched_params = (sched_params_t) {
            .num_reactions_per_level = &num_reactions_per_level[0],
            .num_reactions_per_level_size = (size_t) 3
        };
        lf_sched_init(
            &environments[deadlinetest2_main],
            environments[deadlinetest2_main].num_workers,
            &sched_params
        );
    }
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
